{% set name = "mcrnmf" %}
{% set version = "0.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/m/mcrnmf/mcrnmf-{{ version }}.tar.gz
  sha256: f119c760b9fc3a2847fe3005312a0d2c725c13b54da002915254ba5bc13b4c1c

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }},<3.14
    - numba >=0.61.2
    - numpy >=1.24,<2.3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - mcrnmf
  commands:
    - pip check

about:
  home: https://github.com/siddarthVasudevan/mcrnmf
  doc_url: https://siddarthvasudevan.github.io/mcrnmf/
  license: MIT
  license_file: LICENSE
  summary: "Multivariate Curve Resolution using Nonnegative Matrix Factorization"

extra:
  recipe-maintainers:
    - siddarthVasudevan
