{% set name = "mcrnmf" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{version}}

source:
  path: ../../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python >=3.11.9
    - numpy >=1.26.4
    - numba >=0.60.0

about:
  home: https://github.com/yourusername/mcrnmf
  license: MIT
  summary: "Multivariate Curve Resolution using Nonnegative Matrix Factorization"

extra:
  recipe-maintainers:
    - siddarthVasudevan
